[package]
name = "dsi-dis"
version = "0.1.0"
edition = "2021"
authors = ["Aetias <aetias@outlook.com>"]
license = "MIT"
repository = "https://github.com/AetiasHax/dsi-dis"
readme = "README.md"
description = "Command-line interface for disassembling code inside Nintendo DS ROMs."
publish = false

[[bin]]
name = "dsidis"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
clap-num = "1.1.1"
ds-rom = "0.1.0"
serde = "1.0.204"
serde_yml = "0.0.11"
unarm = { version = "1.4.0", default-features = false, features = ["arm", "thumb", "v5te"] }
