pub(crate) mod ctor;
pub(crate) mod data;
pub(crate) mod exception;
mod function_branch;
mod function_start;
pub mod functions;
mod illegal_code;
mod inline_table;
pub(crate) mod jump_table;
pub(crate) mod main;
pub mod secure_area;
